# docker compose up

version: "3.6"
services:
  portable-gitlab:
    image: "gitlab/gitlab-ce:rc"
    container_name: "gitlab"
    environment:
      GITLAB_SKIP_UNMIGRATED_DATA_CHECK: "true"
      GITLAB_OMNIBUS_CONFIG: |
        external_url = "http://localhost:8002"
    ports:
      - "8002:80"
      - "8443:443"
      - "8022:22"
    volumes:
      - ./data/config:/etc/gitlab
      - ./data/logs:/var/log/gitlab
    shm_size: "256m"
    restart: no